services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - '${PGADMIN_PORT}:80'

#  redis:
#    image: redis:7
#    restart: always
#    volumes:
#      - ./redis_data:/data
#    command: [ "redis-server", "--save", "60", "1", "--appendonly", "yes" ]
#    ports:
#      - '6379'

  backend:
    image: openjdk:17
    container_name: backend
    restart: always
    volumes:
      - ./build/libs/hzfarm.jar:/app/hzfarm.jar
      - ./.env:/.env
      - ./logs:/logs
    env_file:
      - .env
    command: [ "java", "-jar", "/app/hzfarm.jar" ]
    depends_on:
      - db
#      - rabbitmq
#      - minio
    ports:
      - '${BACKEND_PORT}:8080'
