server:
  port: 8080
  address: 0.0.0.0

house-info:
  FARM:
    width: 2
    height: 2
    levels:
      1:
        price: 0
        cows: 6
      2:
        price: 200
        cows: 8
      3:
        price: 300
        cows: 10
    skins:
      - { id: 1001, price: 200 }
      - { id: 1002, price: 300 }

  HOUSE:
    width: 2
    height: 2
    levels:
      1:
        price: 0
        cows: 6
      2:
        price: 200
        cows: 8
      3:
        price: 300
        cows: 10
    skins:
      - { id: 1001, price: 200 }
      - { id: 1002, price: 300 }

  DECOR:
    skins:
      - { id: 3001, price: 300,  width: 1, height: 1 }
      - { id: 3002, price: 200, width: 2, height: 1 }
      - { id: 3003, price: 100, width: 2, height: 2 }

spring:
  application:
    name: Happy-Zombie-Farm

  config:
    import: optional:file:.env[.properties]

  profiles:
    default: house-info

  liquibase:
    enabled: true

  datasource:
    url:  ${POSTGRES_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  #  cache:
  #    type: redis
  #
  #  data:
  #    redis:
  #      host: redis
  #      port: 6379

  #  rabbitmq:
  #    host: rabbitmq
  #    port: ${RABBITMQ}

  web:
    resources:
      add-mappings: true

      static-locations: classpath:/static/,classpath:/public/,file:uploads/

logging:
  level:
    root: INFO
    hz_farm: DEBUG
    org.springframework.web: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: logs/hz_farm.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


