houses-info:
  type:
    FARM:
      width: 2
      height: 2
      levels:
        0:
          price: 0
          cows: 5
        1:
          price: 10
          cows: 6
        2:
          price: 15
          cows: 8
        3:
          price: 20
          cows: 10
      skins:
        basic: { price: 20 }
        winter: { price: 30 }

    STORAGE:
      width: 2
      height: 2
      levels:
        0:
          price: 0
          max-brain: 6
          max-meat: 6
        1:
          price: 100
          max-brain: 200
          max-meat: 1000
        2:
          price: 150
          max-brain: 300
          max-meat: 1500
        3:
          price: 250
          max-brain: 500
          max-meat: 2500
      skins:
        basic: { price: 20 }
        winter: { price: 30 }

    DECOR:
      skins:
        tree: { price: 30, width: 1, height: 1 }
        light: { price: 20, width: 2, height: 1 }
        stone: { price: 10, width: 2, height: 2 }