server:
  port: 8080
  address: 0.0.0.0

security:
  jwt:
    secret: ${JWT_SECRET}
    access-expiration-ms: 900000     # 15 минут
    refresh-expiration-ms: 1209600000 # 14 дней

spring:
  application:
    name: Happy-Zombie-Farm

  config:
    import: optional:file:.env[.properties]

  graphql:
    schema:
      locations: classpath:graphql/
    graphiql:
      enabled: true
      path: /graphiql

  profiles:
    default: houses-info, game-logic

  jackson:
    default-property-inclusion: non_null

  liquibase:
    enabled: true

  datasource:
    url:  ${POSTGRES_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  #  cache:
  #    type: redis
  #
  #  data:
  #    redis:
  #      host: redis
  #      port: 6379

  #  rabbitmq:
  #    host: rabbitmq
  #    port: ${RABBITMQ}

  web:
    resources:
      add-mappings: true

      static-locations: classpath:/static/,classpath:/public/,file:uploads/

logging:
  level:
    root: INFO
    hz_farm: DEBUG
    org.springframework.web: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: logs/hz_farm.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


